In [1]:
import shutup
shutup.please()

import gym
import src.environments.continuous.stock_trading  

import numpy as np
import pandas as pd 

In [2]:
env = gym.make('StockTradingEnvironment-v0', use_technical_indicators= [
    "macd",
    "boll_ub",
    "boll_lb",
    "rsi_30",
    "cci_30",
    "dx_30",
    "close_30_sma",
    "close_60_sma",
])

In [3]:
pd.read_csv('src/environments/continuous/stock_trading/datasets/67b906a1ca1d5e7e03dd20f0c89fd03c/targets.csv').targets.iloc[0]

7.01746749877929

In [4]:
env.train_dataframe_id_range,env.test_dataframe_id_range

([0, 315], [316, 395])

In [5]:
env.load_dataset_by_index(0)
env.df

open       high        low      close     volume  day  \
date                                                                     
2018-01-08  43.587502  43.902500  43.482498  41.573772   82271200    0   
2018-01-09  43.637501  43.764999  43.352501  41.569000   86336000    1   
2018-01-11  43.647499  43.872501  43.622501  41.795528   74670800    3   
2018-01-12  44.044998  44.340000  43.912498  42.227123  101672400    4   
2018-01-16  44.474998  44.847500  44.035000  42.012512  118263600    1   
...               ...        ...        ...        ...        ...  ...   
2018-04-30  40.532501  41.814999  40.459999  39.566917  169709600    0   
2018-05-01  41.602501  42.299999  41.317501  40.486298  214277600    1   
2018-05-02  43.807499  44.437500  43.450001  42.274780  266157600    2   
2018-05-03  43.970001  44.375000  43.610001  42.351402  136272800    3   
2018-05-04  44.562500  46.062500  44.542500  44.012989  224805200    4   

               vix  turbulence      macd    boll_ub  ...  neg_title  \
date                                                 ...              
2018-01-08  0.0952    0.061082 -0.003477  41.870444  ...   0.000000   
2018-01-09  0.1008    0.060920 -0.004579  41.805620  ...   0.000000   
2018-01-11  0.0988    0.061166  0.003795  41.864027  ...   0.244000   
2018-01-12  0.1016    0.071771  0.027654  42.256032  ...   0.000000   
2018-01-16  0.1166    0.177656  0.032756  42.292433  ...   0.000000   
...            ...         ...       ...        ...  ...        ...   
2018-04-30  0.1593    0.219233 -0.531165  43.128501  ...   0.000000   
2018-05-01  0.1549    0.087350 -0.454444  43.132534  ...   0.000000   
2018-05-02  0.1597    0.129608 -0.246744  43.287283  ...   0.040364   
2018-05-03  0.1590    0.045915 -0.075106  43.422290  ...   0.080706   
2018-05-04  0.1477    0.068189  0.192563  43.958449  ...   0.092333   

            neu_title  pos_title  compound_title  neg_body  neu_body  \
date                                                                   
2018-01-08   1.000000   0.000000        0.000000  0.008000  0.934000   
2018-01-09   0.946800   0.053200        0.088080  0.026400  0.919000   
2018-01-11   0.756000   0.000000       -0.296525  0.041000  0.863750   
2018-01-12   1.000000   0.000000        0.000000  0.126000  0.874000   
2018-01-16   0.931667   0.068333        0.067433  0.030000  0.849333   
...               ...        ...             ...       ...       ...   
2018-04-30   1.000000   0.000000        0.000000  0.022500  0.877500   
2018-05-01   1.000000   0.000000        0.000000  0.000000  0.962000   
2018-05-02   0.826455   0.133182        0.110127  0.063545  0.853364   
2018-05-03   0.836706   0.082588        0.003965  0.077765  0.838176   
2018-05-04   0.907667   0.000000       -0.116867  0.066333  0.829000   

            pos_body  compound_body      aapl  fear greed  
date                                                       
2018-01-08  0.058000       0.963700  0.395833        0.75  
2018-01-09  0.055000       0.684980  0.397083        0.75  
2018-01-11  0.095250       0.636025  0.379167        0.77  
2018-01-12  0.000000      -0.893400  0.371667        0.79  
2018-01-16  0.120667       0.729800  0.378333        0.75  
...              ...            ...       ...         ...  
2018-04-30  0.100500       0.939450  0.418333        0.42  
2018-05-01  0.038000       0.381800  0.450417        0.38  
2018-05-02  0.083091       0.339791  0.431250        0.39  
2018-05-03  0.084235       0.158376  0.411667        0.32  
2018-05-04  0.104333      -0.184567  0.415833        0.40  

[76 rows x 26 columns]

In [6]:
env.success_threshold

0.029911279488266853

In [7]:
import pandas as pd
episode_targets = []
for i in range(env.n_dataframes):
    env.load_dataset_by_index(i)
    raw_slice = env.df 
    episode_targets.append([
                    env.get_episode_target(raw_slice),
                    raw_slice.iloc[env.lookback-1].open,
                    raw_slice.iloc[env.lookback-1].low,
                    raw_slice.iloc[env.lookback-1].high,
                    raw_slice.iloc[env.lookback-1].close,
                    raw_slice.iloc[env.lookback-1].volume,
                ])




pd.DataFrame(episode_targets,columns=['targets','open','low','high','close','volume']).to_csv(env.df_path+'/targets.csv', index=False)

In [8]:
episode_columns = ['targets','close','open','high','low','volume']

#pd.DataFrame([[1,2],[1,2]],columns=['a','b'])
#np.array(episode_targets).shape ,=['targets','close','open','high','low','volume']).
pd.DataFrame(episode_targets,columns=episode_columns)

targets      close       open       high        low       volume
0     7.017467  44.325001  44.205002  44.860001  42.215191  130756400.0
1     7.335903  44.312500  43.299999  44.325001  41.542770  204420400.0
2     7.548981  43.627499  42.632500  43.737499  40.801189  166116000.0
3     7.862625  42.540001  41.767502  42.540001  40.050072  202561600.0
4     8.504280  41.382500  41.174999  41.842499  39.814007  184192800.0
..         ...        ...        ...        ...        ...          ...
390  19.386944  54.432499  54.389999  55.032501  53.860348   84632400.0
391  19.453281  54.990002  54.779999  55.205002  54.056297   73274800.0
392  19.984016  55.264999  54.860001  55.712502  54.563301  101360000.0
393  18.982254  55.502499  55.092499  55.939999  54.119972   88242400.0
394  19.159805  55.345001  54.367500  55.639999  53.328846  221652400.0

[395 rows x 6 columns]

In [9]:
state = env.reset()

In [10]:
state

array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  6.85134973e-03,  6.20976220e-03,
         7.80428865e-03,  9.85838413e-03,  2.04042511e-02,
         7.50000000e-01,  1.84899998e-01,  6.14018505e-02,
        -8.04895286e+02,  4.34562703e+03,  3.97330317e+03,
         5.16904171e-01,  3.48498055e-02,  6.30187414e-04,
         4.21134849e+03,  4.16333310e+03,  4.43333333e-02,
         8.55166667e-01,  1.00666667e-01,  6.70333333e-02,
         7.13333333e-02,  8.46166667e-01,  8.25000000e-02,
         2.03333333e-03,  3.95833333e-01,  2.20000000e-01],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
         1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         1.00000000e+00, -4.45089175e-03, -4.59780638e-04,
         9.91069610e-04, -4.67531450e-03, -2.10394036e-01,
         5.00000000e-01,  2.02399998e-01,  2.82656450e-02,
        -6.81147295e+03, -9.20288324e+03, -8.36046180e+

In [11]:
next_state = env.step([1])
next_state 

(array([[ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          1.00000000e+00, -4.45089175e-03, -4.59780638e-04,
          9.91069610e-04, -4.67531450e-03, -2.10394036e-01,
          5.00000000e-01,  2.02399998e-01,  2.82656450e-02,
         -6.81147295e+03, -9.20288324e+03, -8.36046180e+03,
          5.02836337e-01, -7.38403251e-02,  4.14342102e-02,
         -8.88685774e+03, -8.77995747e+03,  7.70000000e-02,
          7.91333333e-01,  1.31666667e-01, -2.38666667e-02,
          8.40000000e-02,  8.68333333e-01,  4.73333333e-02,
         -5.26066667e-01,  4.06250000e-01,  1.80000000e-01],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.00000000e+00,  0.00000000e+00,
          1.00000000e+00,  1.83658761e-02,  5.25740182e-03,
          9.89103689e-03,  1.88178116e-02, -2.09906367e-02,
          2.50000000e-01,  2.04699993e-01,  5.32764216e-02,
         -5.52645540e+02,  2.30184124e+

In [12]:
next_state[0][0] == state[1]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [13]:
# env.reset()
# for i in range(100):
#     next_state, reward, done, _ = env.step(0)
#     print(i, reward,done)#,next_state[-1])
#     if done:
#         break

In [14]:
len(env.df),env.window_size, env.lookback, env.window_size+ env.lookback

(76, 66, 10, 76)

In [15]:
# prices = [5,2,1,7,0,6,3]

# """
# # mins = min de inicio até i inclusive 
#     0 - 5
#     1 - 2
#     2 - 2
#     3 - 2
# # maxs = max de i até fim inclusive
#     0 - 6
#     1 - 6
#     2 - 6
#     3 - 3
# """

# mins = [] #[5,2,2,2]
# maxs = [] #[6,6,6,3]

# ### MINS
# # i = 0 -> prices [0 -> 1] [0:1]
# # mins.append(min(prices[0:1]))
# ### MAXS
# # i = 0 -> prices[0:]
# # i = 1 -> prices[1:]
# # prices[3:]

# for i in range(len(prices)):
#     mins.append(min(prices[0:i+1]))
#     maxs.append(max(prices[i:]))
    
# #mins,maxs
# global_max_single_trade_profit = 0
# for i in range(len(prices)):
#     _min = mins[i]
#     _max = maxs[i]
    
#     print('At {} could have bought at {} and sold at {} so it had {} profit'.format(
#         i,
#         _min,
#         _max,
#         _max-_min
#     ))
#     local_max_single_trade_profit = _max-_min
#     if local_max_single_trade_profit > global_max_single_trade_profit:
#         global_max_single_trade_profit = local_max_single_trade_profit

# print()
# print('Best case scenario would have a profit of {}'.format(global_max_single_trade_profit))

In [16]:
# for i in range(len(prices)):
#     mins.append(min(prices[0:i+1]))
#     maxs.append(max(prices[i:]))
    
# #mins,maxs
# global_max_single_trade_profit = 0
# for i in range(len(prices)):
#     _min = mins[i]
#     _max = maxs[i]
    
#     print('At {} could have bought at {} and sold at {} so it had {} profit'.format(
#         i,
#         _min,
#         _max,
#         _max-_min
#     ))
#     local_max_single_trade_profit = _max-_min
#     if local_max_single_trade_profit > global_max_single_trade_profit:
#         global_max_single_trade_profit = local_max_single_trade_profit

# print()
# print('Best case scenario would have a profit of {}'.format(global_max_single_trade_profit))

In [17]:
# prices = env.df.close.values

# mins = [] 
# maxs = [] 

# for i in range(len(prices)):
#     mins.append(min(prices[0:i+1]))
#     maxs.append(max(prices[i:]))
# #     
# #mins,maxs
# global_max_single_trade_profit = 0
# for i in range(len(prices)):
#     _min = mins[i]
#     _max = maxs[i]
    
#     print('At {} could have bought at {} and sold at {} so it had {} profit'.format(
#         i,
#         _min,
#         _max,
#         _max-_min
#     ))
#     local_max_single_trade_profit = _max-_min
#     if local_max_single_trade_profit > global_max_single_trade_profit:
#         global_max_single_trade_profit = local_max_single_trade_profit

# print()
# print('Best case scenario would have a profit of {}'.format(global_max_single_trade_profit))

In [18]:
#prices * (0.5)
#env.fees['BUY']

In [19]:
# env.n_dataframes

In [20]:
# targets = []
# for i in range(env.n_dataframes):
#     env.load_dataset_by_index(i)
#     target = env.calculate_episode_target(env.df)
#     targets.append(target)
    
# targets

In [21]:
# import pandas as pd
# pd.DataFrame(targets,columns=['targets']).to_csv(env.df_path+'/targets.csv', index=False)

In [22]:
#pd.read_csv(env.df_path+'/targets.csv')

In [23]:
from src.agents.actor_critic.a2c import A2CAgent

In [24]:
def environment():
    env = gym.make('StockTradingEnvironment-v0',
                   use_technical_indicators= [
        "macd",
        "boll_ub",
        "boll_lb",
        "rsi_30",
        "cci_30",
        "dx_30",
        "close_30_sma",
        "close_60_sma",
    ])
    
    #env.success_threshold =0.1
    return env


In [25]:
agent=A2CAgent(environment,batch_size=5000, epochs=25, actor_learning_rate=0.000025,critic_learning_rate=0.000025)
environment().success_threshold

0.029911279488266853

In [26]:
agent.learning_log.episodes

0

In [ ]:
agent.env.mode = "train"
agent.learning_log.episodes = 0
agent.learn(
    timesteps=-1, 
    log_every=100,
    success_threshold_lookback=1000,
    success_strict=True,
    
)

Episode * 100 * Worker * False * Moving Avg Reward is ==> 0.03484 * Last Reward was ==> -0.20176
Episode * 200 * Worker * False * Moving Avg Reward is ==> -0.01298 * Last Reward was ==> -0.02654
Episode * 300 * Worker * False * Moving Avg Reward is ==> -0.00992 * Last Reward was ==> -0.05180
Episode * 400 * Worker * False * Moving Avg Reward is ==> 0.01180 * Last Reward was ==> -0.00490


In [ ]:
agent.env.mode = "test"
scores = []
success = 0

for i in range(100):
    state = agent.env.reset()
    score = 0
    reward = 0
    done = False
    initial_portfolio = agent.env.portfolio_value
    step = 0
    while not done:
                
        #state = np.expand_dims(state, axis=0)
        action, action_onehot, prediction = agent.act(state)
        # Retrieve new state, reward, and whether the state is terminal
        next_state, reward, done, _ = agent.env.step(action)
        #print(action, reward, agent.env.portfolio_value)
        # Memorize (state, action, reward) for training
        #self.buffer.remember(np.expand_dims(state, axis=0), action_onehot, reward)
        # Update current state
        if done :
            if step < 65:
                success +=1
        step+=1
        state = next_state
        score += reward
    
    #print(score,initial_portfolio, agent.env.portfolio_value)
    scores.append(score)
    
print(np.mean(scores))
print(min(scores))
print(max(scores))
print(success)